### ISSUE TITLE
New Widget: Complex Chart

### ISSUE THREAD

**Issue by knowthelist** [knowthelist/fhem-tablet-ui#12]
ToDo: Create a widget that shows feature rich charts for logFiles or logDB. Example: from nesges
http://fhem.de/TabletUI_1.png
Status: unassigned

**Comment by nesges** [comment]
Voraussetzung dafür wäre eine Schicht, die die Logdaten zur Verfügung stellt. fhem bietet dazu eine Lösung im get Befehl von FileLog und DbLog. Beispiel:

```
get DBLOG1 - - 2015-03-27_00:00:00 2015-03-27_13:33:00 W_HUMID:temperature W_HUMID:humidity
```

liefert:

```
2015-03-27_00:34:57 19.2 
2015-03-27_01:21:56 19 
[...]
2015-03-27_13:00:59 17.8 
#W_HUMID:temperature::: 
2015-03-27_00:00:04 53 
2015-03-27_00:00:47 54 
[...]
2015-03-27_12:43:43 53 
#W_HUMID:humidity::: 
```

Diese Daten müssen zusammengeführt und für DYGraphs (http://dygraphs.com/; oder eine andere JS-Library) aufbereitet werden. Ich mache das bisher per PHP, das in JS zu implementieren ist sicher spannend.

**Comment by knowthelist** [comment]
genau, als ich das im commandref entdeckt habe, stand der Beschluss, dass anzugehen. 
Eine Zwischenschicht habe ich noch nicht geplant, erst mal mit  Ajax als Einzelaufruf. Eine Machbarkeitsstudie ist schon am entstehen. EInfacher Parser für Zeit und Value und mit SVG den Plot. WIrd für das Simpelchart der erste Einstieg für mich. ....

**Comment by SirUli** [comment]
Ich vermute, dass man mit den aktuellen Chart-Engines dieses Issue schließen kann?

**Comment by knowthelist** [comment]
Fulfilled by the awesome Chart-Widget
