### ISSUE TITLE
New Widget: Simple Chart

### ISSUE THREAD

**Issue by knowthelist** [knowthelist/fhem-tablet-ui#13]
ToDo: Create a widget to show abstractly a chart to show from logFile. Very simple, just a orange  line
Status: assigned to setstate

**Comment by nesges** [comment]
Siehst du eine Möglichkeit neben Readings auch Internals aus Fhem zu lesen? Damit wäre die Einbindung von Fhem Plots ein Kinderspiel, da alle benötigten Infos bei den SVGs im Internal "DEF" stehen. Beispiel:

DEF: DBLOG1:SVG_DBLOG_B_HEIZUNG_1:CURRENT
->
SVG-URL: /fhem/SVG_showLog?dev=SVG_DbLog_B_HEIZUNG_1&logdev=DBLOG1&gplotfile=SVG_DBLOG_B_HEIZUNG_1&logfile=CURRENT

**Comment by knowthelist** [comment]
Erste funktionierende Alpha Version vom simplechart habe ich gerade für Infozwecke hochgeladen

**Comment by nesges** [comment]
Funktioniert prima! Hab's grade mit Variablen ausgestattet und ein paar Defaultwerte gesetzt. Ausserdem gebe ich dem div 100% height/width, damit sich der Chart übers ganze Widget ausbreitet. Das SVG-Attribut "viewBox" blicke ich aber noch nicht so ganz.

**Comment by knowthelist** [comment]
ich denke, der Ajax und Redraw Teil muss in die Update Function. Dann wird es beim Start und dann bei jedem Shortpollinterval neu geladen. Das Shortpollinterval müssten wir dann noch per Meta tag konfigurierbar machen. Oder ein eigenes unabhängiges Update per Timer innerhalb des Widgets.
$('polyline')  uns $('svg') passt auch noch nicht. Das muss noch per var elem = $(this).find('svg'); geholt werden. Sonst sind wir nicht fit für Multi-Instanzen

**Comment by knowthelist** [comment]
nicht das wir parallel dran arbeiten. :-) Wie wollen wir uns abstimmen?

**Comment by nesges** [comment]
Mach du nur weiter hier dran! :-) Hatte die Änderungen nur eh schon für eigene Tests gebraucht, und man muss ja nicht alles doppelt machen. Eigenes Update-Interval wäre wahrscheinlich sinnvoll. Für "simplecharts" reicht zwar wahrscheinlich das normale, aber sobald die Charts komplexer werden, kann ein reload schonmal dauern. Bei manchen meiner Plots bin ich ganz froh, dass die ausschliesslich manuell upgedatet werden.

**Comment by nesges** [comment]
Schön wäre noch, wenn die aktuell auf 0 bis 24 Uhr fixierte x-Achse flexibel einstellbar wäre (mindate bis maxdate würde sich anbieten, aber auch maxdate-X bis maxdate).
