### ISSUE TITLE
Bug:  Thermostat sizes not as readme

### ISSUE THREAD

**Issue by malcb** [knowthelist/fhem-tablet-ui#134]
The readme says that thermostat class sizes are: mini, small, big, bigger, readonly (knob has mini, small, large, readonly).  The ones that work are large (150px) and big (210px).  Default is 100px.

The tablet css defines large, big, bigger, bigplus, grande and small.  It would be useful to be able to have larger sizes than 210px (i.e. bigger, bigplus, grande).

**Comment by malcb** [comment]
For those who can't wait for a fix then you need to add lines in widget_knob.js at line 38 to define bigger etc..  Just duplicate line 38 and change it.

**Comment by malcb** [comment]
However, the current temperature and valve position are a hard code size in the js.  So making the thermostat bigger does not increase the size of the font.  It's pretty poor not to be able to resize the font and not to have it scale.

**Comment by knowthelist** [comment]
fixed
