### ISSUE TITLE
Not working with Midori

### ISSUE THREAD

**Issue by theftf** [knowthelist/fhem-tablet-ui#138]
Tablet UI is not working with midori (a greate small browser eg. for pi with touchscreen)...

**Comment by knowthelist** [comment]
What is not working in detail? Not starting? Slow start up? click / touch issue?
I know problems with Midori on Ubuntu Desktop. JS tells document.ontouchstart = true, but has no touchscreen. This cause problems with FTUI buttons and knobs. Also dynamicload doesn't work reliable (browser reports timeouts). There is no solution for that until now

**Comment by knowthelist** [comment]
solved now
