### ISSUE TITLE
Problem mit Touscreen und Chrome

### ISSUE THREAD

**Issue by ghost** [knowthelist/fhem-tablet-ui#157]
Unter Windows 10 kann ich, wenn ich die Tablet-UI mit Chrome (aktuelle Version 52) aufrufe, die UI nicht mit der Maus benutzen, wenn ich meinen Computer mit Touchscreen benutze.
Über das Touchscreen selbst geht es, und auch wenn ich einen anderen Browser benutze. Die normale FHEM-Oberfläche funktioniert auch. So wie die beiden Widgets circlemenu und select. An meinem Computer ohne Touchscreen funktioniert die Bedienung per Maus problemlos.

Getestet habe ich alle Widget aus der mitgelieferte index-example.html, davon funktionieren nur circlemenu und select.

**Comment by knowthelist** [comment]
Solved
