### ISSUE TITLE
Symbol-Ergänzung widget-weather Proplanta

### ISSUE THREAD

**Issue by umbm** [knowthelist/fhem-tablet-ui#166]
Ich habe bei Proplanta einen bisher nicht definierten Wetterzustand festgestellt, wobei also kein entsprechendes Symbol zugeordnet ist.

Ich schlage als Ergänzung Zeile 146 vor:
`'Spruehregen':                 'mist.png',`

**Comment by knowthelist** [comment]
Danke, ist übernommen
