### ISSUE TITLE
support of english wind-direction

### ISSUE THREAD

**Issue by franconianmetal** [knowthelist/fhem-tablet-ui#181]
Hi,
proposal for english wind-direction in widget:
`data-lang="en"` (default is german)

changed wind_direction.js as attached.

Is it possible for you to check it in? feel free to change it
Regards!
[widget_wind_direction.js.gz](https://github.com/knowthelist/fhem-tablet-ui/files/650275/widget_wind_direction.js.gz)

**Comment by knowthelist** [comment]
typo -> correct: 'en' translation
Thanks for your patch
