### ISSUE TITLE
Hardcoded 'WEB' in new check for longpoll

### ISSUE THREAD

**Issue by schmidHolger** [knowthelist/fhem-tablet-ui#198]
I just updated ftui in fhem and ran into a new error message popping up:
**Uncaught TypeError: Cannot read property 'val' of undefined**

It turns out that the new check for longpoll is causing this issue.

In fhem-tablet-ui.js, the following check was just added:
`
if ('WebSocket' in window && 
            ftui.config.longPollType === 'websocket' &&
            ftui.deviceStates['WEB'] &&
            ftui.deviceStates['WEB'].longpoll.val === 'websocket') {
`

This leads to some problems:

- If not 'WEB' is used as device, this checks for the wrong device

- Once I add "longpoll websocket" to my device, this does not show up in ftui.deviceStates[\<myDevice\>]. A console.log(ftui.deviceState[\<myDevice\>] is showing all attribues but not the "longpoll" one so `ftui.deviceState[\<myDevice\>].longpoll.val` is producing this error

**Comment by knowthelist** [comment]
use the meta tag "web_device"

<meta name='web_device' content='WEB'>

**Comment by malcb** [comment]
Do you mean
`<meta name='web_device' content='yes'>`
needs to be added to index.html header or something different?

**Comment by knowthelist** [comment]
If your dont use WEB as name for your FHEMWEB device, configure the name as this meta parameter. 

<meta name='web_device' content='MyWEB'>
