### ISSUE TITLE
push widget ignores data-countdown and fires data-set-off immediately

### ISSUE THREAD

**Issue by twenta** [knowthelist/fhem-tablet-ui#220]
Hi,

I use the push widget in the following manner:
`                            <div data-type="push" data-device="Heizungen" data-set-on="controlMode boost" data-countdown=300 data-set-off="controlMode auto"></div>`

No countdown is started and data-set-on and data-set-off are fired at the same time. (I am aware that the data-set-off command might be unnecessary here)

**Comment by knowthelist** [comment]
This behaviour is expected here. This is a built in mode for Push. Press -> send data-set-on value. Release -> send data-set-off value.

**Comment by twenta** [comment]
Sorry, I misinterpreted the description. Thanks for the clarification
