### ISSUE TITLE
Update Widget_gds

### ISSUE THREAD

**Issue by miggi92** [knowthelist/fhem-tablet-ui#233]
Hello,

is it possible to update the gds widget to support the new DWD module?
https://wiki.fhem.de/wiki/DWD_OpenData

Thanks :)

Best regards 
Miguel

**Comment by roman1528** [comment]
https://forum.fhem.de/index.php/topic,89570.msg884526.html#msg884526

widget_dwdopendata

gds is depricated^^

can be closed^^
gz
