### ISSUE TITLE
Wrong symbol display since merge pull request #225 from fhainz/patch-4

### ISSUE THREAD

**Issue by meier81** [knowthelist/fhem-tablet-ui#252]
Hi,
since the merge pull request # 225 from fhainz / patch-4 my symbols are displayed totally wrong, see here:

<img width="94" alt="fail example 1" src="https://user-images.githubusercontent.com/40598096/81106079-4270df00-8f15-11ea-943f-9d84cfd8e1a6.PNG">
<img width="387" alt="fail example 2" src="https://user-images.githubusercontent.com/40598096/81106088-4866c000-8f15-11ea-8d8b-87dbcf7dac56.PNG">

The symbols were displayed correctly before the merge, see here:

<img width="89" alt="before merge example 1" src="https://user-images.githubusercontent.com/40598096/81106099-4ac91a00-8f15-11ea-861f-ef3c7af9a42a.PNG">
<img width="373" alt="before merge example 2" src="https://user-images.githubusercontent.com/40598096/81106108-4c92dd80-8f15-11ea-885c-e9ec4b023ce5.PNG">

Here is an excerpt of my definition:

<td>
	<div data-type="symbol"
		 data-device="Abfall"
		 data-get="Abfallkalender_GelberSackinBadDuerkheim_days"
		 data-warn="Abfallkalender_GelberSackinBadDuerkheim_days"
		 data-warn-on="([0-9]|[1-9][0-9]|off)"
		 data-states='["off","0","1","([2-9]|[1][0-9])"]'
		 data-icons='["fs-bag","fs-bag fa-spin","fs-bag fa-blink","fs-bag"]'
		 data-colors='["#FFFF00","#FFFF00","#FFFF00","#FFFF00"]'>
	</div>
</td>

Please look at the mistake again, thank you in advance.

**Comment by cptpeppy** [comment]
I can confirm this issue regarding symbols after latest patch.

**Comment by knowthelist** [comment]
fixed with ab6e80a2de1505e6c15c5e256e0b93548cbd5616
