### ISSUE TITLE
access denied index.html

### ISSUE THREAD

**Issue by eboelens** [knowthelist/fhem-tablet-ui#253]
Hi , TABLETUI runs with HTTPSRV in Fhem on a RaspberryPI

Edit the index.html is not possible 

[ File '/opt/fhem/www/tablet/index.html' is unwritable ]
[ Error writing /opt/fhem/www/tablet/index.html: Permission denied ]

Any Idea what I can do please ?

Erik

**Comment by knowthelist** [comment]
just make it writable with chmod
