### ISSUE TITLE
Synchronous XMLHttpRequest on the main thread is deprecated

### ISSUE THREAD

**Issue by nesges** [knowthelist/fhem-tablet-ui#27]
Die JS-Warning: 

"Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/."

wird verursacht durch fhem-tablet-ui.js, Zeile 31:

```
$.ajax({
    url: dir+'/'+name+'.js',
    dataType: "script",
    cache: true,
    async: false,
    context:{name: name},
            [...]
```

bzw. genauer durch "async:false". Gibt es einen Grund, dass dieser ajax-Request synchron sein muss? Ich habe testweise auf "async:true" gestellt und keinen Unterschied bemerkt.

**Comment by knowthelist** [comment]
async geht hier nicht, es kann passieren, dass das Init noch nicht durch ist und das Update schon laufen will. Dann werden "halbe" Elemente angezeigt. Das kann erst wieder angeschaltet werden, wenn wir  das erste Update verzögern, bis die Anzahl der fertigen Ist-Soll Inits gleich ist. Ist aber auch gefährlich, wenn mal ein Init versagt, dann wird garnix updated.
