### ISSUE TITLE
widget_thermostat: getClimaValues unterdrückt alphanumerische Werte

### ISSUE THREAD

**Issue by nesges** [knowthelist/fhem-tablet-ui#43]
```
desired: getPart(val_desired,'(\\d+[.,]?\\d+).*'),
```

Das ist neu, oder? Thermostat-Devices können auch Werte wie "off" oder "boost" liefern, die damit unterdrückt werden. Ausserdem etwas höher:

```
var val_desired = getDeviceValue( device, 'get');
var val_desired = ( state && state.indexOf('set_') < 0 ) ? val_desired : getPart(state,2);
```

Eins von beiden muss sicher weg :-) Ich auch grade, von daher halt ich's mal so fest ohne dem weiter nachzu gehen.

**Comment by nesges** [comment]
Hab mir das jetzt nochmal angesehen. In Zeile 8 ist offenbar nur das "var" zuviel. Ist das eine Anpassung für ein bestimmtes Device, das "Schrott" liefert? Das getPart() in den Zeilen 12 und 13 hat sicher einen Sinn, der in die gleiche Richtung geht - der erschliesst sich mir nur nicht. Was soll/muss damit erreicht werden? Falls der Regex drin bleiben muss, müssten mindestens noch die mit den Parametern data-off und data-boost definierten Werte zugelassen werden; aber vielleicht reicht ja auch ein ein wenig gnädigerer Regex.

```
    temp: getPart(val_temp,'(\\S+).*'),
    desired: getPart(val_desired,'(\\S+).*'),
```

**Comment by knowthelist** [comment]
upps, da da habe ich mal was versucht und bin unterbrochen worden. Danke fürs fixen

**Comment by knowthelist** [comment]
Wenn man bei HM die Soll-Temp verändert, steht einige Sekunden folgendes im STATE:
set_desired-temp 15
Das muss beachtet werden

**Comment by nesges** [comment]
Alles klar, danke! :)
