### ISSUE TITLE
Volume Widget: unable to preset fgcolor 

### ISSUE THREAD

**Issue by knowthelist** [knowthelist/fhem-tablet-ui#67]
Warum kann man beim  Volume Widget kein default für fgcolor setzten? 

Jetzt:      'fgColor': $(this).data('fgcolor'),

Ich möchte:            'fgColor': $(this).data('fgcolor') || '#007733',

Aber in $(this).data('fgcolor') ist schon ein Wert drin, wo ich nicht weiß, wo der herkommt. Oder ich übersehe was bei mir? Im HTML habe ich nix gesetzt. Beim Thermostat geht es bei mir. 

Ich habe eine Funktion geschrieben, die die Defaults zusätzlich im CSS File sucht (für unterschiedliche Themes -> mobil: heller und blaue Buttons), dafür brauche ich das.

**Comment by nesges** [comment]
Man kann schon einen Default setzen:

```
$(this).data('fgcolor', $(this).data('fgcolor') || 'red');
base.init_attr($(this));
```

Wichtig ist nur, dass man ihn vor dem Aufruf von base.init_attr() setzt, sonst wird er aus widget_knob.init_attr() gesetzt.

**Comment by knowthelist** [comment]
Okay, danke, werde ich heute Abend mal testen. fgColor wird direkt im jQuery knob gesetzt, glaube ich

**Comment by knowthelist** [comment]
ich hatte den init_attr Teil eingeklappt und deswegen nicht gesehen, ich Gehirn ;-)
