### ISSUE TITLE
data-set in select

### ISSUE THREAD

**Issue by prinzkafka** [knowthelist/fhem-tablet-ui#72]
Da scheint sich ein kleiner Fehler im Select Widget eingeschlichen zu haben. An FHEM wird immer das Reading geschickt, welches im data-get steht.

**Comment by nesges** [comment]
Das wird geschickt, wenn data-get gesetzt und data-set nicht gesetzt ist - inwiefern ist das problematisch?

**Comment by prinzkafka** [comment]
dass es auch geschickt wird, wenn ein data-get UND ein data-set gesetzt sind 

data-type="select" data-device="radio"  data-get="file" data-set="playfile"

bei der Konstellation wird "file" gesendet und nicht "playfile"

ich benutze das MPD Modul in FHEM, da gibt es playfile als set, aber nicht als reading, dafür gibt es aber das reading "file", in dem dann der Musiklink steht, welcher vorher per set playfile geschickt wurde ( damit steuere ich mopidy (Musikserver) auf dem Raspberry)

**Comment by knowthelist** [comment]
Danke, für das weitere Feedback und die Erklärung. Fehler gefunden und gefixed

**Comment by prinzkafka** [comment]
Vielen lieben Dank
